[server]
url = "http://localhost:55555"
db_connection_string = "PostgreSQL connection string"
expiry_check_interval_seconds = 21600

[lichess]
domain = "lichess.org"
client_id = "Lichess OAuth client ID here"
client_secret = "Lichess OAuth client secret here"
team_id = "Lichess team ID"
team_admin = "Lichess user ID of team administrator"
personal_api_token = "Lichess personal API token"

[azolve]
api = "Azolve API url"
api_pwd = "Azolve API password"
