[org]
long_name = "Organisation long name here (e.g. English Chess Federation)"
short_name = "Organisation short name here (e.g. ECF)"
icon = "favicon URL"
image = "banner image URL"
team_id = "Lichess team ID"
timezone = "Organisation timezone (e.g. Europe/London)"
referral_link = "Link to where a non-member can sign up"
authentication_secret = "PIN" # String describing how the organisation will verify your identity, for example "PIN" or "password".
                              # Appears on the homepage and above the second field on the linking form.
memberid_placeholder = "Placeholder/explanation about the member ID (appears IN the member ID field on the form)"
password_placeholder = "Placeholder/explanation about the password/PIN field (appears IN the password field on the form)"
password_explanation = "Further explanation about the password (appears UNDER the password field on the form)"
memberid_pattern = "Regular expression for valid membership ID"

[expiry]
membership_month = 8
membership_day = 31 # The last month and day on which an organisation's membership is valid
renewal_month = 9
renewal_day = 14 # The last month and day on which a member can renew their membership before being kicked from the Lichess team

[server]
url = "http://localhost:55555"
db_connection_string = "PostgreSQL connection string"
expiry_check_interval_seconds = 21600

[lichess]
domain = "lichess.org"
client_id = "Lichess OAuth client ID here"
client_secret = "Lichess OAuth client secret here"
team_admin = "Lichess user ID of team administrator"
personal_api_token = "Lichess personal API token"

[azolve]
api = "Azolve API url"
api_pwd = "Azolve API password"
