url = "http://localhost:55555"
lichess = "lichess.org"
client_id = "Lichess OAuth client ID here"
client_secret = "Lichess OAuth client secret here"
connection_string = "PostgreSQL connection string"
azolve_api = "Azolve API url"
azolve_api_pwd = "Azolve API password"