[development]
address = "127.0.0.1"
port = 44444

[staging]
address = "127.0.0.1"
port = 44444

[production]
address = "127.0.0.1"
port = 44444
# secret key doesn't really need to be configured,
# given how short-lived our session cookies are